import {
  blueA,
  blueDarkA,
  crimsonA,
  cyanA,
  cyanDarkA,
  greenA,
  irisA,
  jadeA,
  orangeA,
  plumA,
  purpleA,
  purpleDarkA,
  redA,
  sageA,
  skyA,
  slateA,
  tealA,
  whiteA,
  yellowA,
} from "@radix-ui/colors";

export const stacksBackend = [
  {
    title: "Python",
    src: "/icons-langs/python.svg",
    alt: "python",
    color: yellowA.yellowA2,
  },
  {
    title: "Node",
    src: "/icons-langs/nodejs.svg",
    alt: "nodejs",
    color: greenA.greenA3,
  },
  {
    title: "Express",
    src: "/icons-libs-frameworks/express.svg",
    alt: "express",
    color: sageA.sageA5,
  },
  {
    title: "Nest",
    src: "/icons-libs-frameworks/nestjs.svg",
    alt: "nestjs",
    color: redA.redA3,
  },
  {
    title: "Prisma",
    src: "/icons-libs-frameworks/prisma.svg",
    alt: "prisma",
    color: purpleA.purpleA4,
  },
  {
    title: "Supabase",
    src: "/icons-libs-frameworks/supabase.svg",
    alt: "supabase",
    color: jadeA.jadeA3,
  },
  {
    title: "Adonis",
    src: "/icons-libs-frameworks/adonisjs.svg",
    alt: "adonis",
    color: irisA.irisA4,
  },
  {
    title: "Jest",
    src: "/icons-libs-frameworks/jest.svg",
    alt: "jest",
    color: crimsonA.crimsonA3,
  },
  {
    title: "CSharp",
    src: "/icons-langs/csharp.svg",
    alt: "csharp",
    color: plumA.plumA3,
  },
  {
    title: "Typescript",
    src: "/icons-langs/typescript.svg",
    alt: "typescript",
    color: cyanA.cyanA3,
  },
  {
    title: "PHP",
    src: "/icons-langs/php.svg",
    alt: "php",
    color: purpleA.purpleA3,
  },
  {
    title: "Twig",
    src: "/icons-libs-frameworks/twig.svg",
    alt: "twig",
    color: greenA.greenA3,
  },
  {
    title: "Rust",
    src: "/icons-langs/rust.svg",
    alt: "rust",
    color: orangeA.orangeA2,
  },
];

export const stacksFrontend = [
  {
    title: "React",
    src: "/icons-libs-frameworks/react.svg",
    alt: "reactjs",
    color: skyA.skyA3,
  },
  {
    title: "Vue",
    src: "/icons-libs-frameworks/vuejs.svg",
    alt: "vue",
    color: tealA.tealA3,
  },
  {
    title: "Tailwind CSS",
    src: "/icons-libs-frameworks/tailwindcss.svg",
    alt: "tailwindcss",
    color: blueA.blueA3,
  },
  {
    title: "Bootstrap",
    src: "/icons-libs-frameworks/bootstrap.svg",
    alt: "bootstrap",
    color: purpleDarkA.purpleA2,
  },
  {
    title: "Next",
    src: "/icons-libs-frameworks/nextjs.svg",
    alt: "nextjs",
    color: whiteA.whiteA2,
  },
  {
    title: "Javascript",
    src: "/icons-langs/javascript.svg",
    alt: "javascript",
    color: yellowA.yellowA2,
  },
  {
    title: "Typescript",
    src: "/icons-langs/typescript.svg",
    alt: "typescript",
    color: cyanA.cyanA3,
  },
  {
    title: "CSS",
    src: "/icons-langs/css3.svg",
    alt: "css",
    color: blueA.blueA3,
  },
  {
    title: "HTML",
    src: "/icons-langs/html.svg",
    alt: "html",
    color: redA.redA3,
  },
];

export const stacksTools = [
  {
    title: "Docker",
    src: "/icons-tools/docker.svg",
    alt: "docker",
    color: cyanDarkA.cyanA2,
  },
  {
    title: "Git",
    src: "/icons-tools/git.svg",
    alt: "git",
    color: redA.redA3,
  },
  {
    title: "Github",
    src: "/icons-tools/github.svg",
    alt: "github",
    color: whiteA.whiteA1,
  },
  {
    title: "VSCode",
    src: "/icons-tools/vscode.svg",
    alt: "vscode",
    color: blueDarkA.blueA2,
  },
  {
    title: "Visual Studio",
    src: "/icons-tools/visual-studio.svg",
    alt: "vscode",
    color: purpleDarkA.purpleA2,
  },
  {
    title: "Linux",
    src: "/icons-tools/linux.svg",
    alt: "linux",
    color: slateA.slateA7,
  },
  {
    title: "Trello",
    src: "/icons-tools/trello.svg",
    alt: "trello",
    color: blueDarkA.blueA3,
  },
  {
    title: "Vite",
    src: "/icons-tools/vite.svg",
    alt: "vite",
    color: plumA.plumA3,
  },
  {
    title: "Postgres",
    src: "/icons-tools/postgresql.svg",
    alt: "postgresql",
    color: skyA.skyA3,
  },
];
